#!/bin/bash

set -e

if [ -z $1 ]; then
  echo "find nodes in osm using the OR of node attributes"
  echo "For instance, find neighborhoods OR water founters: "
  echo "$0 <path to file.pbf.osm> place=neighborhood amenity=drinking_water"
  exit -1
fi
TARGET_FILE=$1
BIN_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
OSMOSIS_BIN="osmosis/bin/osmosis"

echo "launching osmosis.."

$BIN_DIR/$OSMOSIS_BIN \
  --read-pbf $TARGET_FILE \
  --tag-filter accept-nodes "${@:3}" \
  --write-xml output.osm

